name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  # Esto te permite correrlo a mano desde la web si querés
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Sincroniza el repo de GitHub con el Space de HF
          git push --force https://SebaVida:$HF_TOKEN@huggingface.co/spaces/SebaVida/VidaCV main
